branch-defaults:
  master:
    environment: api-my-moto-dev
    group_suffix: null
deploy:
  artifact: target/gerenciador-0.0.1-SNAPSHOT.jar
global:
  application_name: api-my-moto
  branch: null
  default_ec2_keyname: null
  default_platform: Java 8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
